server:
  port: 9001

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/retail?useUnicode=true
    username: root
    password: 113089Mysqlpw@
    driver-class-name: com.mysql.cj.jdbc.Driver

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id:
#        rewards: rewards

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #dialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        current_session_context_class: thread

application:
  port:
    inventory: 9002
    product: 9000
    user: 8999





